### PR TITLE
Remove async and object-assign

### PR DESCRIPTION
**Pull request by thom4parisot**

### CODE REVIEW

**Comment by borisschapira** [comment]
Thanks! I've completly stopped to maintain this project. Do you want to adopt it ?

**Comment by thom4parisot** [comment]
Happy to pair the two of us and embedding newcomers rather than maintaining on my own (kind of not maintain mine very well too :-p)

**Comment by thom4parisot** [comment]
By the way, if you have no interest maintaining the project now I'm ready to take over and of course keep you as a maintainer as well! 😄

**Comment by borisschapira** [comment]
Of course, what should I do?

**Comment by thom4parisot** [comment]
Well I guess simply adding me as a contributor on this page would suffice: https://www.npmjs.com/package/hexo-algolia/access

Then it's up to you:
- adding me as a collaborator so as I have _write access_: https://github.com/borisschapira/hexo-algolia/settings/collaboration
- transferring the ownership of the repo: https://github.com/borisschapira/hexo-algolia/settings

Maybe one day you'll leave jekyll so who knows :-p

**Comment by borisschapira** [comment]
You're added as a contributor to the npm repo and the ownership of the repo is transferred to you. Enjoy!

**Pull request merged**
